### ISSUE TITLE
Package OpenCV 3.1

### ISSUE THREAD

**Issue by phrack** [openpnp/opencv#7] opened 2016-08-15 16:14 UTC
Would be wonderful to have OpenCV 3 packaged as nicely as this repo does it. OpenCV 3 is faster and contains more complete Java bindings than 2.

**Comment by vonnieda** [comment] 2016-08-15 17:55
I tried to move to OpenCV 3 a while back but all of the Java tests were completely broken. Have you built OpenCV 3.1 with Java bindings and found it to be stable?

**Comment by phrack** [comment] 2016-08-16 00:18
It compiles cleanly on Arch using this PKGBUILD to "cheat": https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=opencv-java. Notice that it uses a patch for gcc6 -- that's because OpenCV doesn't compile in its current form with gcc6 because it can't find standard headers like stdlib.h, but it should with gcc5.

**Comment by phrack** [comment] 2016-08-16 00:19
Actually, looks like the gcc6 error is fixed in master: https://github.com/opencv/opencv/issues/6517.

**Comment by phrack** [comment] 2016-08-16 00:42
I don't know when they'll release again, they seem due, but I can confirm master with Java bindings is building cleanly with gcc6.

**Comment by gedaiu** [comment] 2016-12-06 07:06
when you'll release the OpenCV 3 package?

**Comment by vonnieda** [comment] 2016-12-06 14:15
@gedaiu I'll see about getting a release together this week. I had been hoping that OpenCV would release a new version soon but who knows when it will be. It's been almost a year since the last 3.x release.

**Comment by gedaiu** [comment] 2016-12-07 08:27
thanks!

**Comment by vonnieda** [comment] 2016-12-10 17:41
@gedaiu @phrack I started working on this, but unfortunately it's currently not possible to build 3.1.0 on MacOS Sierra, which is what I am running due to this issue: https://github.com/opencv/opencv/pull/7159

The issue is fixed in the head of OpenCV, but since they have not released that yet I won't build a package for it.

So, it looks like we will need to wait for the next version of the 3.x line to be released.

**Comment by vonnieda** [comment] 2016-12-10 17:44
Here is some discussion about the release of 3.2. It was supposed to be released by May, then in Q4 2016. Q4 is almost up, so we can hope, but maybe not hold our breath :) 

http://answers.opencv.org/question/101612/is-there-any-enthusiasm-for-making-point-releases-311/

**Comment by vonnieda** [comment] 2016-12-23 22:56
Looks like OpenCV 3.2 was released today, so I will see about getting it packaged up next week!

**Comment by vonnieda** [comment] 2016-12-27 03:42
3.2.0-0 has been released! Please give it a try and let me know if you run into any issues.

```
<dependency>
      <groupId>org.openpnp</groupId>
      <artifactId>opencv</artifactId>
      <version>3.2.0-0</version>
</dependency>
```

**Closed by vonnieda** 2016-12-27 03:42 UTC

**Comment by phrack** [comment] 2016-12-27 15:28
Great work, thanks!

**Comment by vonnieda** [comment] 2016-12-27 15:29
@phrack If you run into problems running on Linux please see https://github.com/openpnp/opencv/issues/10. I am planning to do another release today to address this.

**Comment by phrack** [comment] 2016-12-27 15:33
We'll probably play around on Windows first. Not sure that any of us will get to it this week. I, at least, am mostly taking the holidays off from tech.
