### ISSUE TITLE
Open CV distributed with openpnp can't load image from a IP camera 

### ISSUE THREAD

**Issue by gevant** [openpnp/opencv#90] opened 2023-03-13 23:56 UTC
Using:  VideoCapture class and camera.open("udp://0.0.0.0:1111"), Videoio.CAP_FFMPEG);

Getting:  
CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.6.0) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\videoio\src\cap.cpp:201: error: (-2:Unspecified error) could not open 'udp://xxxx' in function 'cv::VideoCapture::open'
]
	at org.opencv.videoio.VideoCapture.open_0(Native Method)
	at org.opencv.videoio.VideoCapture.open(VideoCapture.java:222)
....

On Windows 10

At the same time on a same machine, a manually copied original OpenCV jarfile and dll when used without maven and with "-Djava.library.path=xxx" connects to the ip camera without issues and receives video.

I validated openCV by trying to load png test image to the Mat with Opencv from file with no issues before getting exception trying open camera.  

Same JDK 18  is used in both cases. 

The only difference is 
opencv_videoio_ffmpeg460_64.dll is missing in the jarfile 
Is it possible to add it to the maven distribution, it is quite popular use case to get video feed

**Comment by vonnieda** [comment] 2023-03-14 01:29
Looks like this is because it is trying to use ffmpeg to capture video, and we do not currently ship ffmpeg. 

I'll close this as a duplicate of #74. Please follow that issue for details.

**Closed as completed by vonnieda** 2023-03-14 01:29 UTC
