### ISSUE TITLE
UnsatisfiedLinkError on MAC with Maven using CascadeClassifier

### ISSUE THREAD

**Issue by martinfluchmfmfmf** [openpnp/opencv#37] opened 2018-09-03 20:11 UTC
Hi, 

is there anybody who can give me a hint whats the reason for the following error: 

```
[2018-09-03 22:46:12,335]-[Hotswap] ERROR quattro.App - An error occurred while starting the application:
java.lang.UnsatisfiedLinkError: no opencv_java342 in java.library.path: [/Users/martin/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2654)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:876)
```

my test class has
```
static{ 
		nu.pattern.OpenCV.loadShared();
		//nu.pattern.OpenCV.loadLocally();
		System.loadLibrary(Core.NATIVE_LIBRARY_NAME); 
		}
```

my pom.xml references 
```
    <!-- https://mvnrepository.com/artifact/org.openpnp/opencv -->
<dependency>
    <groupId>org.openpnp</groupId>
    <artifactId>opencv</artifactId>
    <version>3.4.2-0</version>
</dependency>

<!-- https://mvnrepository.com/artifact/org.openpnp/openpnp-capture-java -->
<dependency>
    <groupId>org.openpnp</groupId>
    <artifactId>openpnp-capture-java</artifactId>
    <version>0.0.12</version>
</dependency>
```

the relevant code seems to be
```
	capture=new OpenPnpCapture();
		devices = capture.getDevices();
		faceCascade = new CascadeClassifier();
```

CascadeClassfiers are part of opencv aren't they? 

Looks similar to #24, I'm using java 10

**Comment by vonnieda** [comment] 2018-09-04 17:46
Duplicate of https://github.com/openpnp/opencv/issues/33. The library is not currently compatible with Java 10.

**Closed by vonnieda** 2018-09-04 17:46 UTC
